# Generated by Django 4.1.2 on 2022-10-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='Слаг'),
        ),
    ]
